django_dangun/dangun_app/urls.py
from django.urls import path
from . import views
from .views import set_region_certification
from django.contrib.auth import views as auth_views


app_name = 'dangun_app'

urlpatterns = [
    
    path('test/', views.test, name='test'),

    path('alert/<str:alert_message>/<str:redirect_url>/', views.alert, name='alert'),


    path('', views.main, name='main'),
    path('login/', views.custom_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='dangun_app:main'), name='logout'),
    path('register/', views.register, name='register'),
    path('trade/', views.trade, name='trade'),
    path('trade_post/<int:pk>/', views.trade_post, name='trade_post'),
    path('write/', views.write, name='write'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('create_form/', views.create_post, name='create_form'),
    path('location/', views.location, name='location'),
    path('set_region/', views.set_region, name='set_region'),
    path('set_region_certification/', set_region_certification, name='set_region_certification'),
    path('search/', views.search, name='search'),
    path('chat/', views.chat_view, name='chat'),

    # 채팅
    path("chat_index", views.index, name='index'),  
    path('chat_index/<int:pk>/', views.chat_room, name='chat_room'),
    path('create_or_join_chat/<int:pk>/', views.create_or_join_chat, name='create_or_join_chat'),
    path('get_latest_chat/', views.get_latest_chat_no_pk, name='get_latest_chat_no_pk'),
    path('get_latest_chat/<int:pk>/', views.get_latest_chat, name='get_latest_chat'),

    path('confirm_deal/<int:post_id>/', views.ConfirmDealView.as_view(), name='confirm_deal'),

    path('admin_main/', views.admin_main, name='admin_main'),  # [관리자] 메인 페이지
    path('admin_user_list/', views.admin_user_list, name='admin_user_list'),  # [관리자] 유저 정보 관리 리스트
    path('admin_user_delete/<int:user_id>/', views.admin_user_delete, name='admin_user_delete'),  # [관리자] 유저 정보 삭제
    path('admin_user_modify/<int:user_id>/', views.admin_user_modify, name='admin_user_modify'),  # [관리자] 유저 정보 수정    
]

django_dangun/dangun_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dangun_app.urls')), 
    path('favicon.ico', RedirectView.as_view(url='/static/dangun_app/favicon.ico', permanent=True)),
    path('accounts/', include('allauth.urls')),
    path('auth/', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_dangun/dangun_app/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=200)
    price = models.IntegerField()
    description = models.TextField()
    location = models.CharField(max_length=100)
    images = models.ImageField(upload_to='post_images/') 
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, to_field='username')
    created_at = models.DateTimeField(auto_now_add=True, null=True) 

    product_reserved = models.CharField(max_length=1, default='N')  # 예약 여부
    product_sold = models.CharField(max_length=1, default='N')  # 판매 여부
    buyer = models.ForeignKey(User, related_name='purchased_posts', null=True, blank=True, on_delete=models.SET_NULL) # 구매자


    view_num = models.PositiveIntegerField(default=0)  # 조회 수
    chat_num = models.PositiveIntegerField(default=0)  # 채팅 수

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_at']

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    region = models.CharField(max_length=100, null=True)
    region_certification = models.CharField(max_length=1, default='N')
    type = models.CharField(max_length=100, null=True)  # type 필드 추가
    
    def __str__(self):
        return f'{self.user.username} Profile'
    

class ChatRoom(models.Model):
    room_number = models.AutoField(primary_key=True)
    starter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='started_chats')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_chats')
    created_at = models.DateTimeField(auto_now_add=True)
    latest_message_time = models.DateTimeField(null=True, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='chat_rooms', null=True, blank=True)


    def __str__(self):
        return f'ChatRoom: {self.starter.username} and {self.receiver.username}'

class Message(models.Model):
    chatroom = models.ForeignKey(ChatRoom, on_delete=models.CASCADE, related_name='messages')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='authored_messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Message: {self.author.username} at {self.timestamp}'

    class Meta:
        ordering = ['timestamp']

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # 새 메시지가 저장될 때마다 chatroom의 latest_message_time을 업데이트
        self.chatroom.latest_message_time = self.timestamp
        self.chatroom.save()



class Region(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # 사용자와의 관계
    address = models.CharField(max_length=255)  # 주소를 저장할 필드

    def __str__(self):
        return self.address

django_dangun/dangun_app/forms.py
from django import forms
from .models import Post


class CustomLoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': '아이디를 입력해주세요', 'class': 'login-input'}),
        label='아이디',
        label_suffix='', 
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': '비밀번호를 입력해주세요', 'class': 'login-input'}),
        label='비밀번호',
        label_suffix='', 
    )

class CustomRegistrationForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': '아이디를 입력해주세요', 'class': 'login-input'}),
        label='아이디',
        label_suffix='', 
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': '비밀번호를 입력해주세요', 'class': 'login-input'}),
        label='비밀번호',
        label_suffix='', 
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': '비밀번호를 다시 입력해주세요', 'class': 'login-input'}),
        label='비밀번호 확인',
        label_suffix='', 
    )
    

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'price', 'description', 'location', 'images']

django_dangun/dangun_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.db.models import Q
from django.utils.decorators import method_decorator
from django.views import View
from datetime import timedelta, datetime
from django.http import Http404

from .models import Post,UserProfile, ChatRoom, Message

from .forms import CustomLoginForm, CustomRegistrationForm, PostForm

# Alert용 화면
def alert(request, alert_message, redirect_url='location'): # default 값을 'location'으로 설정
    context = {
        'alert_message': alert_message,
        'redirect_url': redirect_url
    }
    return render(request, 'dangun_app/alert.html', context)



# 채팅 ################################################################################

# 채팅테스트

def index(request): 
    return render(request, 'dangun_app/chat_index.html')


# 채팅방 열기
def chat_room(request, pk):
    user = request.user
    chat_room = get_object_or_404(ChatRoom, pk=pk)

    # 내 ID가 포함된 방만 가져오기
    chat_rooms = ChatRoom.objects.filter(
            Q(receiver_id=user) | Q(starter_id=user)
        ).order_by('-latest_message_time')  # 최신 메시지 시간을 기준으로 내림차순 정렬
    
    # 각 채팅방의 최신 메시지를 가져오기
    chat_room_data = []
    for room in chat_rooms:
        latest_message = Message.objects.filter(chatroom=room).order_by('-timestamp').first()
        if latest_message:
            chat_room_data.append({
                'chat_room': room,
                'latest_message': latest_message.content,
                'timestamp': latest_message.timestamp,
            })

    # 상대방 정보 가져오기
    if chat_room.receiver == user:
        opponent = chat_room.starter
    else:
        opponent = chat_room.receiver

    opponent_user = User.objects.get(pk=opponent.pk)


    # post의 상태 확인 및 처리
    if chat_room.post is None:
        seller = None
        post = None
    else:
        seller = chat_room.post.user
        post = chat_room.post

    return render(request, 'dangun_app/chat_room.html', {
        'chat_room': chat_room,
        'chat_room_data': chat_room_data,
        'room_name': chat_room.pk,
        'seller': seller,
        'post': post,
        'opponent': opponent_user,
    })


# 채팅방 생성 또는 참여
def create_or_join_chat(request, pk):
    post = get_object_or_404(Post, pk=pk)
    user = request.user
    chat_room = None
    created = False

    # 채팅방이 이미 존재하는지 확인
    chat_rooms = ChatRoom.objects.filter(
        Q(starter=user, receiver=post.user, post=post) |
        Q(starter=post.user, receiver=user, post=post)
    )
    if chat_rooms.exists():
        chat_room = chat_rooms.first()
    else:
        # 채팅방이 존재하지 않는 경우, 새로운 채팅방 생성
        chat_room = ChatRoom(starter=user, receiver=post.user, post=post)
        chat_room.save()
        created = True

    return JsonResponse({'success': True, 'chat_room_id': chat_room.pk, 'created': created})


# 가장 최근 채팅방 가져오기
@login_required
def get_latest_chat(request, pk):
    user = request.user
    # 1) 해당 pk인 채팅방 중 가장 최신 채팅방으로 리디렉션
    try:
        latest_chat_with_pk = ChatRoom.objects.filter(
            Q(post_id=pk) &
            (Q(receiver=user) | Q(starter=user))
        ).latest('latest_message_time')
        return JsonResponse({'success': True, 'chat_room_id': latest_chat_with_pk.room_number})
    except ChatRoom.DoesNotExist:
        pass

    # 2) 위 경우가 없다면 내가 소속된 채팅방 전체 중 가장 최신 채팅방으로 리디렉션
    try:
        latest_chat = ChatRoom.objects.filter(
            Q(receiver=user) | Q(starter=user)
        ).latest('latest_message_time')
        return JsonResponse({'success': True, 'chat_room_id': latest_chat.room_number})

    # 3) 모두 없다면 현재 페이지로 리디렉션
    except ChatRoom.DoesNotExist:
        return JsonResponse({
            'success': False, 
            'alert_message': '진행중인 채팅이 없습니다.'
        })

        
# nav/footer에서 채팅하기 눌렀을 때
@login_required
def get_latest_chat_no_pk(request):
    user = request.user
    try:
        latest_chat = ChatRoom.objects.filter(
            Q(receiver=user) | Q(starter=user),
            latest_message_time__isnull=False
        ).latest('latest_message_time')
        return redirect('dangun_app:chat_room', pk=latest_chat.room_number)

    except ChatRoom.DoesNotExist:
        return redirect('dangun_app:alert', alert_message='진행중인 채팅이 없습니다.', redirect_url='current')
    
@method_decorator(login_required, name='dispatch')
class ConfirmDealView(View):
    def post(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        user = request.user

        previous_url = request.META.get('HTTP_REFERER')
        url_parts = previous_url.split('/')
        original_post_id = url_parts[-2] if url_parts[-1] == '' else url_parts[-1]

        chat_room = get_object_or_404(ChatRoom, room_number=original_post_id)


        if chat_room.starter == user:
            other_user = chat_room.receiver
        else:
            other_user = chat_room.starter

        if chat_room is None:
            messages.error(request, 'Chat room does not exist.')
            return redirect('dangun_app:trade')
        
        # buyer를 설정하고, product_sold를 Y로 설정
        post.buyer = chat_room.receiver if chat_room.starter == post.user else chat_room.starter
        post.product_sold = 'Y'
        post.save()
        
        # 거래가 확정되면 새로고침
        return redirect('dangun_app:chat_room', pk=chat_room.room_number)

# 채팅 끝 ################################################################################

# 메인 화면
def main(request):
    top_views_posts = Post.objects.filter(product_sold='N').order_by('-view_num')[:4] 
    return render(request, 'dangun_app/main.html', {'posts': top_views_posts})


# 테스트용 화면
def test(request):
    return render(request, 'dangun_app/test.html')

# 중고거래 화면
def trade(request):
    top_views_posts = Post.objects.filter(product_sold='N').order_by('-view_num')
    return render(request, 'dangun_app/trade.html', {'posts': top_views_posts})

# 중고거래상세정보(각 포스트) 화면
def trade_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    cookie_name = f'main_{pk}_viewed'
    if cookie_name not in request.COOKIES:
        if request.user.is_authenticated:
            if request.user != post.user:
                post.view_num += 1
        else:
            post.view_num += 1

        post.save()
        # 조회수 증가 막는 기간 : 하루
        expires = datetime.now() + timedelta(days=1)
        expires = expires.strftime('%a, %d-%b-%Y %H:%M:%S GMT')
        response = render(request, 'dangun_app/trade_post.html', {'post': post})
        response.set_cookie(cookie_name, 'true', expires=expires)
        return response

    try:
        user_profile = UserProfile.objects.get(user=post.user)
    except UserProfile.DoesNotExist:
            user_profile = None

    context = {
        'post': post,
        'user_profile': user_profile,
        'chat_room': chat_room,
    }

    return render(request, 'dangun_app/trade_post.html', context)


# 거래글쓰기 화면
@login_required
def write(request):
    try:
        user_profile = UserProfile.objects.get(user=request.user)
        
        if user_profile.region_certification == 'Y':
            return render(request, 'dangun_app/write.html')
        else:
            return redirect('dangun_app:alert', alert_message='동네인증이 필요합니다.', redirect_url='location')
    except UserProfile.DoesNotExist:
        return redirect('dangun_app:alert', alert_message='동네인증이 필요합니다.', redirect_url='location')

# 거래글수정 화면
def edit(request, id):
    post = get_object_or_404(Post, id=id)
    if post:
        post.description = post.description.strip()
    if request.method == "POST":
        post.title = request.POST['title']
        post.price = request.POST['price']
        post.description = request.POST['description']
        post.location = request.POST['location']
        if 'images' in request.FILES:
            post.images = request.FILES['images']
        post.save()
        return redirect('dangun_app:trade_post', pk=id)

    return render(request, 'dangun_app/write.html', {'post': post})


# 채팅 화면
@login_required
def chat_view(request):
    return render(request, 'dangun_app/chat.html')

# 동네인증 화면
@login_required
def location(request):
    try:
        user_profile = UserProfile.objects.get(user_id=request.user)
        region = user_profile.region
    except UserProfile.DoesNotExist:
        region = None

    return render(request, 'dangun_app/location.html', {'region': region})


# 가입 화면
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.shortcuts import render, redirect
from .forms import CustomRegistrationForm

def register(request):
    error_message = ''
    if request.method == 'POST':
        form = CustomRegistrationForm(request.POST)
        username = request.POST.get('username')
        if User.objects.filter(username=username).exists():
            error_message = "이미 존재하는 아이디입니다."
        elif form.is_valid():
            
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']
            
            # 비밀번호 일치 여부를 확인
            if password1 == password2:
                # 새로운 유저를 생성
                user = User.objects.create_user(username=username, password=password1)
                
                # 유저를 로그인 상태로 만듦
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            
            
                return redirect('dangun_app:login')
            else:
                form.add_error('password2', 'Passwords do not match')
    else:
        form = CustomRegistrationForm()
    
    return render(request, 'registration/register.html', {'form': form, 'error_message': error_message})


# 로그인 화면

django_dangun/dangun_app/templates/dangun_app/admin_user_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>유저 정보 삭제</title>
</head>
<body>
    <h1>유저 정보 삭제</h1>
    <form method="post" action="{% url 'dangun_app:admin_user_delete' user.id %}">
        {% csrf_token %}
        <input type="submit" value="삭제">
    </form>
    <br>
    <a href="{% url 'dangun_app:admin_user_list' %}">뒤로 가기</a>
</body>
</html>

django_dangun/dangun_app/templates/dangun_app/admin_user_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>전체 회원 목록</title>
</head>
<body>
<b><font size="5" color="gray">전체 회원 목록</font></b>
<br><br>
<table border="1" cellspacing="0">
    <tr>
        <th>아이디</th>
        <th>회원 유형</th>
        <th>이름</th>
        <th>비밀번호</th>
        <th>삭제</th>
        <th>수정</th>
    </tr>

    {% for user in user_list %}
    <tr>
        <td>{{ user.id }}</td>
        <td>{{ user.type }}</td>
        <td>{{ user.username }}</td>
        <td>{{ user.password }}</td>
        <td>
            <form method="post" action="{% url 'dangun_app:admin_user_delete' user.id %}">
                {% csrf_token %}
                <input type="submit" value="삭제">
            </form>
        <td>
            <input type="button" value="수정" 
                   onClick="location.href='{% url 'dangun_app:admin_user_modify' user.id %}'">
        </td>
    </tr>
    {% endfor %}
</table>
<br>
<input type="button" value="확인" onClick="location.href='../admin_main'">

</body>
</html>

django_dangun/dangun_app/templates/dangun_app/alert.html
<!DOCTYPE html>
<html>

  <head>
    <title>당근</title>
  </head>

  <body>
    <script type="text/javascript">
      alert('{{ alert_message }}');
      {% if redirect_url == "location" %}
        window.location.href = '{% url "dangun_app:location" %}';
      {% elif redirect_url == "current" %}
        window.history.back();
      {% else %}
        window.history.back();
      {% endif %}
    </script>
  </body>

</html>

django_dangun/dangun_app/templates/dangun_app/chat_room.html
<!-- chat/templates/chat_room.html -->
{% load static%}{% load humanize %}

<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/chat.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}"/>
    <title>채팅하기</title>
  </head>

  <body class="back-ye">
    {% include 'dangun_app/nav.html' %}

    <div class="content-box">
      <div class="container column">
        <div class="post-box flex-box">

          <!-- 채팅선택창 -->
          <div class="chat-select-container">
            <div class="flex-box">

              <!-- 아이디및 체크박스 -->
              <div class="id-box flex-box between">
                <span id="user-name">{{ user.username }}</span><br>

                <div>
                  {% comment %} <label>
                    안읽은 메세지만 보기
                    <input type="checkbox" name="" id="">
                  </label> {% endcomment %}
                </div>
              </div>
            </div>

            <!-- 채팅 리스트 -->
            <div class="chat-list-box flex-box column">
              <!-- 봇 -->
              <div class="chat-box flex-box">
                <div class="ai-profile">
                  <img src="{% static 'img/icon_aibot.png'%}" alt="">
                </div>
                <div>
                  <p class="bold">AI 챗봇</p>
                  <p class="chat-thumb-text">궁금한 내용을 물어보세요!</p>
                </div>
              </div>
              <!-- 채팅방리스트 -->
              {% include 'dangun_app/chat_room_list.html' %}

            </div>
          </div>

          <!-- 채팅창-->
          <div class="chat-main-container">
            <div>
              <div class="contact-info flex-box">
                {{ opponent.username }}

                <span id="room-name" style="display:none">{{ chat_room.pk }}</span>
              </div>

              <!--물품정보-->
              <div class="goods-box flex-box between">
                <div class="flex-box">
                  <div class="selected-thumbnail-box">
                    <img src="{{ post.images.url }}" alt="">
                  </div>
                  <div class="goods-info-box">
                    <p>{{ post.title }}</p>
                    <p class="bold">{{ post.price |intcomma}}원</p>
                  </div>
                </div>
                {% if user.id == post.user.id %}
                    <form method="post" action="{% url 'dangun_app:confirm_deal' post.id %}">
                        {% csrf_token %}
                        <button type="submit">거래확정하기</button>
                    </form>
                {% endif %}
            
              </div>

              <!--채팅창 메인-->

              <div id="chat-log" class="chat-container"></div>

              

            </div>
            <form class="chat-input" action="">
              <textarea name="" id="chat-message-input" cols="30" rows="10" placeholder="메세지를 입력해주세요"></textarea>
              <div>
                <button id="chat-message-submit">전송</button>
              </div>
            </form>
          </div>
        </div>
      </div>
      {% include 'dangun_app/footer.html' %}

    </body>
    <script>
      document.addEventListener("DOMContentLoaded", function () {

        // 주소에서 룸번호 찾기
        const roomName = document
          .getElementById('room-name')
          .textContent
          .trim();

        // 유저 id 찾기
        const userName = document
          .getElementById('user-name')
          .textContent
          .trim();

        // 웹소켓설정
        const chatSocket = new WebSocket('ws://' + window.location.host + '/ws/chat_index/' + roomName + '/');

        //메세지 실시간으로 채팅창에 넣음
        chatSocket.onmessage = function (e) {
          const data = JSON.parse(e.data);
          
          // 메시지의 발신자가 현재 사용자인지 확인
          const isFromMe = data.username === userName;
          
          // 메시지 박스의 CSS 클래스를 설정
          const messageClass = isFromMe ? "from-me" : "";
          
          // 메시지 박스를 동적으로 생성하고 페이지에 추가
          let chatLogTest = document.getElementById("chat-log");
          chatLogTest.innerHTML += `<div class="message-box ${messageClass}">
              <div class="message-text">${data.message}</div>
            </div>`;
        };
        chatSocket.onclose = function (e) {
          console.error('Chat socket closed unexpectedly');
        };

        // 채팅창에 키 들어가있도록 함
        document
          .querySelector('#chat-message-input')
          .focus();

        // 채팅 전송
        document
          .querySelector('#chat-message-input')
          .onkeyup = function (e) {
            if (e.keyCode === 13) { // enter, return
              document
                .querySelector('#chat-message-submit')
                .click();
            }
          };

        document
          .querySelector('#chat-message-submit')
          .onclick = function (e) {
            e.preventDefault();
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({'username': userName, 'message': message}));
            messageInputDom.value = '';
          };
      });
    </script>

  </html>

django_dangun/dangun_app/templates/dangun_app/nav.html
{% load static %}

<nav>
  <div class="container">
    <div class="full-box flex-box between">
      <div class="flex-box">
        <div class="logo">
          <a href="{% url 'dangun_app:main' %}">
            <img src="{% static 'img/logo.png' %}" alt=""/>
          </a>
        </div>
        <div class="nav-buttons">
          <a href="/trade">
            <button id="trade-button">중고거래</button>
          </a>
          {% if user.is_authenticated %}
            <a href="/location">
              <button id="location-button">동네인증</button>
            </a>
          {% endif %}

        </div>
      </div>
      <div class="flex-box gap8">
        <form method="GET" action="{% url 'dangun_app:search' %}">
          <input type="text" id="search" name="search" class="search" placeholder="물품이나 동네를 검색해보세요"/>
        </form>
        {% if user.is_authenticated %}
          <a href="{% url 'dangun_app:get_latest_chat_no_pk' %}" class="ghost-button orange">채팅하기</a>
          <a href="{% url 'dangun_app:logout' %}" class="ghost-button">로그아웃</a>

        {% else %}
          <a href="{% url 'dangun_app:login' %}" class="ghost-button" style="color: #1e1e1e">로그인</a>
        {% endif %}
      </div>
    </div>
  </div>
  <script src="{% static 'js/nav.js' %}"></script>
</nav>

django_dangun/dangun_app/templates/dangun_app/trade.html
{% load custom_filter%}
{% load static %}{% load humanize %}
<!DOCTYPE html>
<html>

  <head>
    <title>중고거래</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/trade.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}"/>
  </head>

  <body>
    {% include 'dangun_app/nav.html' %}
    <div class="content-box">
      <a href="{% url 'dangun_app:write' %}">
        <div class="floating-button">
          거래글쓰기
        </div>
      </a>
      <div class="about-trade">
        <div class="container ">
          <div class="trade-text">
            <h3>믿을만한</br>이웃 간 중고거래</h3>
          <p>동네 주민들과 가깝고 따뜻한 거래를</br>지금 경험해보세요.</p>
      </div>
      <div class="thumbnail-img">
        <img src="{% static 'img/img1.png' %}" alt=""/>
      </div>
    </div>
  </div>

  <div class="post-box">
    <div class="container column center">
      <h1>중고거래 인기매물</h1>
    </div>
    <div class="container column center">
      <div class="full-box trade-box column">
        <div class="flex-box full-box card-container between">
          {% for post in posts %}

            <div class="card-box">
              <a href="{% url 'dangun_app:trade_post' post.pk %}" class="trade-text-link">
                <div class="card-img">
                  {% if post.images %}
                    <img src="{{ post.images.url }}" alt="{{ post.title }}">
                  {% endif %}
                </div>
                <div class="card-info-box">
                  <h5>{{ post.title }}</h5>
                  <p class="bold">{{ post.price |intcomma}}원</p>
                  <p>{{ post.location }}</p>
                  <div class="flex-box">
                    <p>조회
                      {{ post.view_num }}</p>
                    <p>·</p>
                    <p>채팅
                      {{ post.chat_num }}</p>
                  </div>
                </div>
              </a>
            </div>
          {% endfor %}

        </div>
      </div>
    </div>
  </div>
  {% include 'dangun_app/footer.html' %}

</body>

</html>